#
# This file is auto-generated. DO NOT EDIT
# Generated by: autospec.py
#
%define keepstatic 1
Name     : qbittorrent
Version  : 3.0.0
Release  : 16
URL      : file:///insilications/build/clearlinux/packages/qbittorrent/qbittorrent-release-3.0.0.tar.gz
Source0  : file:///insilications/build/clearlinux/packages/qbittorrent/qbittorrent-release-3.0.0.tar.gz
Summary  : No detailed summary available
Group    : Development/Tools
License  : BSD-2-Clause
Requires: qbittorrent-bin = %{version}-%{release}
Requires: qbittorrent-data = %{version}-%{release}
Requires: qbittorrent-man = %{version}-%{release}
BuildRequires : boost-dev
BuildRequires : buildreq-cmake
BuildRequires : buildreq-configure
BuildRequires : buildreq-make
BuildRequires : buildreq-qmake
BuildRequires : libtorrent-rasterbar
BuildRequires : libtorrent-rasterbar-dev
BuildRequires : libtorrent-rasterbar-staticdev
BuildRequires : openssl-dev
BuildRequires : openssl-staticdev
BuildRequires : pkgconfig(Qt5Svg)
BuildRequires : pkgconfig(libsystemd)
BuildRequires : pkgconfig(libtorrent-rasterbar)
BuildRequires : pkgconfig(libudev)
BuildRequires : pkgconfig(openssl)
BuildRequires : pkgconfig(systemd)
BuildRequires : pkgconfig(udev)
BuildRequires : pkgconfig(zlib)
BuildRequires : qttools-dev
BuildRequires : sed
BuildRequires : systemd
BuildRequires : systemd-dev
BuildRequires : systemd-services
BuildRequires : zlib-dev
BuildRequires : zlib-staticdev
# Suppress stripping binaries
%define __strip /bin/true
%define debug_package %{nil}

%description
qBittorrent - A BitTorrent client in Qt
------------------------------------------

%package bin
Summary: bin components for the qbittorrent package.
Group: Binaries
Requires: qbittorrent-data = %{version}-%{release}

%description bin
bin components for the qbittorrent package.


%package data
Summary: data components for the qbittorrent package.
Group: Data

%description data
data components for the qbittorrent package.


%package man
Summary: man components for the qbittorrent package.
Group: Default

%description man
man components for the qbittorrent package.


%prep
%setup -q -n qbittorrent
cd %{_builddir}/qbittorrent

%build
## build_prepend content
./bootstrap.sh
## build_prepend end
unset http_proxy
unset https_proxy
unset no_proxy
export SSL_CERT_FILE=/var/cache/ca-certs/anchors/ca-certificates.crt
export LANG=C.UTF-8
export SOURCE_DATE_EPOCH=1601594702
export GCC_IGNORE_WERROR=1
## altflags1 content
export CFLAGS="-g -O3 -march=native -mtune=native -fgraphite-identity -Wall -Wl,--as-needed -Wl,--build-id=sha1 -Wl,--enable-new-dtags -Wl,--hash-style=gnu -Wl,-O2 -Wl,-z,now -Wl,-z,relro -falign-functions=32 -flimit-function-alignment -fasynchronous-unwind-tables -fdevirtualize-at-ltrans -floop-nest-optimize -fno-math-errno -fno-semantic-interposition -fno-stack-protector -fno-trapping-math -ftree-loop-distribute-patterns -ftree-loop-vectorize -ftree-vectorize -funroll-loops -fuse-ld=bfd -fuse-linker-plugin -malign-data=cacheline -feliminate-unused-debug-types -fipa-pta -flto=16 -fno-plt -mtls-dialect=gnu2 -Wl,-sort-common -Wno-error -Wp,-D_REENTRANT -pipe -ffat-lto-objects -fPIC"
# -ffat-lto-objects -fno-PIE -fno-PIE -m64 -no-pie -fpic -fvisibility=hidden -flto-partition=none
# gcc: -feliminate-unused-debug-types -fipa-pta -flto=16 -Wno-error -Wp,-D_REENTRANT -fno-common
export CXXFLAGS="-g -O3 -march=native -mtune=native -fgraphite-identity -Wall -Wl,--as-needed -Wl,--build-id=sha1 -Wl,--enable-new-dtags -Wl,--hash-style=gnu -Wl,-O2 -Wl,-z,now -Wl,-z,relro -falign-functions=32 -flimit-function-alignment -fasynchronous-unwind-tables -fdevirtualize-at-ltrans -floop-nest-optimize -fno-math-errno -fno-semantic-interposition -fno-stack-protector -fno-trapping-math -ftree-loop-distribute-patterns -ftree-loop-vectorize -ftree-vectorize -funroll-loops -fuse-ld=bfd -fuse-linker-plugin -malign-data=cacheline -feliminate-unused-debug-types -fipa-pta -flto=16 -fno-plt -mtls-dialect=gnu2 -Wl,-sort-common -Wno-error -Wp,-D_REENTRANT -fvisibility-inlines-hidden -pipe -ffat-lto-objects -fPIC"
#
export FCFLAGS="-g -O3 -march=native -mtune=native -fgraphite-identity -Wall -Wl,--as-needed -Wl,--build-id=sha1 -Wl,--enable-new-dtags -Wl,--hash-style=gnu -Wl,-O2 -Wl,-z,now -Wl,-z,relro -falign-functions=32 -flimit-function-alignment -fasynchronous-unwind-tables -fdevirtualize-at-ltrans -floop-nest-optimize -fno-math-errno -fno-semantic-interposition -fno-stack-protector -fno-trapping-math -ftree-loop-distribute-patterns -ftree-loop-vectorize -ftree-vectorize -funroll-loops -fuse-ld=bfd -fuse-linker-plugin -malign-data=cacheline -feliminate-unused-debug-types -fipa-pta -flto=16 -fno-plt -mtls-dialect=gnu2 -Wl,-sort-common -Wno-error -Wp,-D_REENTRANT -pipe -ffat-lto-objects -fPIC"
export FFLAGS="-g -O3 -march=native -mtune=native -fgraphite-identity -Wall -Wl,--as-needed -Wl,--build-id=sha1 -Wl,--enable-new-dtags -Wl,--hash-style=gnu -Wl,-O2 -Wl,-z,now -Wl,-z,relro -falign-functions=32 -flimit-function-alignment -fasynchronous-unwind-tables -fdevirtualize-at-ltrans -floop-nest-optimize -fno-math-errno -fno-semantic-interposition -fno-stack-protector -fno-trapping-math -ftree-loop-distribute-patterns -ftree-loop-vectorize -ftree-vectorize -funroll-loops -fuse-ld=bfd -fuse-linker-plugin -malign-data=cacheline -feliminate-unused-debug-types -fipa-pta -flto=16 -fno-plt -mtls-dialect=gnu2 -Wl,-sort-common -Wno-error -Wp,-D_REENTRANT -pipe -ffat-lto-objects -fPIC"
export CFFLAGS="-g -O3 -march=native -mtune=native -fgraphite-identity -Wall -Wl,--as-needed -Wl,--build-id=sha1 -Wl,--enable-new-dtags -Wl,--hash-style=gnu -Wl,-O2 -Wl,-z,now -Wl,-z,relro -falign-functions=32 -flimit-function-alignment -fasynchronous-unwind-tables -fdevirtualize-at-ltrans -floop-nest-optimize -fno-math-errno -fno-semantic-interposition -fno-stack-protector -fno-trapping-math -ftree-loop-distribute-patterns -ftree-loop-vectorize -ftree-vectorize -funroll-loops -fuse-ld=bfd -fuse-linker-plugin -malign-data=cacheline -feliminate-unused-debug-types -fipa-pta -flto=16 -fno-plt -mtls-dialect=gnu2 -Wl,-sort-common -Wno-error -Wp,-D_REENTRANT -pipe -ffat-lto-objects -fPIC"
#
export LDFLAGS="-g -O3 -march=native -mtune=native -fgraphite-identity -Wall -Wl,--as-needed -Wl,--build-id=sha1 -Wl,--enable-new-dtags -Wl,--hash-style=gnu -Wl,-O2 -Wl,-z,now -Wl,-z,relro -falign-functions=32 -flimit-function-alignment -fasynchronous-unwind-tables -fdevirtualize-at-ltrans -floop-nest-optimize -fno-math-errno -fno-semantic-interposition -fno-stack-protector -fno-trapping-math -ftree-loop-distribute-patterns -ftree-loop-vectorize -ftree-vectorize -funroll-loops -fuse-ld=bfd -fuse-linker-plugin -malign-data=cacheline -feliminate-unused-debug-types -fipa-pta -flto=16 -fno-plt -mtls-dialect=gnu2 -Wl,-sort-common -Wno-error -Wp,-D_REENTRANT -pipe -ffat-lto-objects -fPIC"
#
export AR=gcc-ar
export RANLIB=gcc-ranlib
export NM=gcc-nm
#
export MAKEFLAGS=%{?_smp_mflags}
#
%define _lto_cflags 1
#%define _lto_cflags %{nil}
#
# export PATH="/usr/lib64/ccache/bin:$PATH"
# export CCACHE_NOHASHDIR=1
# export CCACHE_DIRECT=1
# export CCACHE_SLOPPINESS=pch_defines,locale,time_macros
# export CCACHE_DISABLE=1
# LDFLAGS="${LDFLAGS} -Wl,--whole-archive /usr/lib64/libz.a /usr/lib64/libssl.a /usr/lib64/libcrypto.a /usr/lib64/libtorrent-rasterbar.a /usr/lib64/libssl.a /usr/lib64/libcrypto.a /usr/lib64/libz.a -pthread -ldl -lm -lmvec -Wl,--no-whole-archive"
export libtorrent_LIBS="-Wl,--whole-archive /usr/lib64/libtorrent-rasterbar.a -pthread -ldl -lm -lmvec -Wl,--no-whole-archive"
export openssl_LIBS="-Wl,--whole-archive /usr/lib64/libssl.a /usr/lib64/libcrypto.a -pthread -ldl -lm -lmvec -Wl,--no-whole-archive"
export zlib_LIBS="-Wl,--whole-archive /usr/lib64/libz.a -pthread -ldl -lm -lmvec -Wl,--no-whole-archive"
## altflags1 end
##
%define _lto_cflags 1
##
%configure
make  %{?_smp_mflags}  V=1 VERBOSE=1


%install
export SOURCE_DATE_EPOCH=1601594702
rm -rf %{buildroot}
%make_install

%files
%defattr(-,root,root,-)

%files bin
%defattr(-,root,root,-)
/usr/bin/qbittorrent

%files data
%defattr(-,root,root,-)
/usr/share/applications/org.qbittorrent.qBittorrent.desktop
/usr/share/icons/hicolor/128x128/apps/qbittorrent.png
/usr/share/icons/hicolor/128x128/status/qbittorrent-tray.png
/usr/share/icons/hicolor/16x16/apps/qbittorrent.png
/usr/share/icons/hicolor/16x16/status/qbittorrent-tray.png
/usr/share/icons/hicolor/192x192/apps/qbittorrent.png
/usr/share/icons/hicolor/192x192/status/qbittorrent-tray.png
/usr/share/icons/hicolor/22x22/apps/qbittorrent.png
/usr/share/icons/hicolor/22x22/status/qbittorrent-tray.png
/usr/share/icons/hicolor/24x24/apps/qbittorrent.png
/usr/share/icons/hicolor/24x24/status/qbittorrent-tray.png
/usr/share/icons/hicolor/32x32/apps/qbittorrent.png
/usr/share/icons/hicolor/32x32/status/qbittorrent-tray.png
/usr/share/icons/hicolor/36x36/apps/qbittorrent.png
/usr/share/icons/hicolor/36x36/status/qbittorrent-tray.png
/usr/share/icons/hicolor/48x48/apps/qbittorrent.png
/usr/share/icons/hicolor/48x48/status/qbittorrent-tray.png
/usr/share/icons/hicolor/64x64/apps/qbittorrent.png
/usr/share/icons/hicolor/64x64/status/qbittorrent-tray.png
/usr/share/icons/hicolor/72x72/apps/qbittorrent.png
/usr/share/icons/hicolor/72x72/status/qbittorrent-tray.png
/usr/share/icons/hicolor/96x96/apps/qbittorrent.png
/usr/share/icons/hicolor/96x96/status/qbittorrent-tray.png
/usr/share/icons/hicolor/scalable/status/qbittorrent-tray-dark.svg
/usr/share/icons/hicolor/scalable/status/qbittorrent-tray-light.svg
/usr/share/icons/hicolor/scalable/status/qbittorrent-tray.svg
/usr/share/metainfo/org.qbittorrent.qBittorrent.appdata.xml
/usr/share/pixmaps/qbittorrent.png

%files man
%defattr(0644,root,root,0755)
/usr/share/man/man1/qbittorrent.1
